# This workflow will launch at 00:00 every day
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

name: Launch Scala Steward

permissions:
  contents: write
  pull-requests: write

jobs:
  scala-steward:
    if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          git_user_signingkey: true
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.REPO_GITHUB_TOKEN }}
          signing-key: ${{ secrets.GPG_SIGNING_KEY_ID }}
          sign-commits: true